# Generated by Django 4.0.3 on 2022-09-16 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_id_quiz_quiz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 16, 57, 56, 279636)),
        ),
    ]
