# Generated by Django 4.0.3 on 2022-09-19 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('quiz', '0003_alter_quiz_quiz_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_classroom', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 19, 50, 23, 780870)),
        ),
    ]
