# Generated by Django 4.0.3 on 2022-09-19 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_classroom_alter_quiz_quiz_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quistion_list',
            new_name='question_list',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 20, 25, 36, 660240)),
        ),
    ]
