# Generated by Django 4.0.3 on 2022-09-25 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_quistion_list_quiz_question_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 10, 14, 19, 576659)),
        ),
    ]
